INSERT INTO `bible_books` (`id`, `name`) VALUES (1, 'Genesis');
INSERT INTO `bible_books` (`id`, `name`) VALUES (2, 'Exodus');
INSERT INTO `bible_books` (`id`, `name`) VALUES (3, 'Leviticus');
INSERT INTO `bible_books` (`id`, `name`) VALUES (4, 'Numbers');
INSERT INTO `bible_books` (`id`, `name`) VALUES (5, 'Deuteronomy');
INSERT INTO `bible_books` (`id`, `name`) VALUES (6, 'Joshua');
INSERT INTO `bible_books` (`id`, `name`) VALUES (7, 'Judges');
INSERT INTO `bible_books` (`id`, `name`) VALUES (8, 'Ruth');
INSERT INTO `bible_books` (`id`, `name`) VALUES (9, '1 Samuel');
INSERT INTO `bible_books` (`id`, `name`) VALUES (10, '2 Samuel');
INSERT INTO `bible_books` (`id`, `name`) VALUES (11, '1 Kings');
INSERT INTO `bible_books` (`id`, `name`) VALUES (12, '2 Kings');
INSERT INTO `bible_books` (`id`, `name`) VALUES (13, '1 Chronicles');
INSERT INTO `bible_books` (`id`, `name`) VALUES (14, '2 Chronicles');
INSERT INTO `bible_books` (`id`, `name`) VALUES (15, 'Ezra');
INSERT INTO `bible_books` (`id`, `name`) VALUES (16, 'Nehemiah');
INSERT INTO `bible_books` (`id`, `name`) VALUES (17, 'Esther');
INSERT INTO `bible_books` (`id`, `name`) VALUES (18, 'Job');
INSERT INTO `bible_books` (`id`, `name`) VALUES (19, 'Psalms');
INSERT INTO `bible_books` (`id`, `name`) VALUES (20, 'Proverbs');
INSERT INTO `bible_books` (`id`, `name`) VALUES (21, 'Ecclesiastes');
INSERT INTO `bible_books` (`id`, `name`) VALUES (22, 'Song of Solomon');
INSERT INTO `bible_books` (`id`, `name`) VALUES (23, 'Isaiah');
INSERT INTO `bible_books` (`id`, `name`) VALUES (24, 'Jeremiah');
INSERT INTO `bible_books` (`id`, `name`) VALUES (25, 'Lamentations');
INSERT INTO `bible_books` (`id`, `name`) VALUES (26, 'Ezekiel');
INSERT INTO `bible_books` (`id`, `name`) VALUES (27, 'Daniel');
INSERT INTO `bible_books` (`id`, `name`) VALUES (28, 'Hosea');
INSERT INTO `bible_books` (`id`, `name`) VALUES (29, 'Joel');
INSERT INTO `bible_books` (`id`, `name`) VALUES (30, 'Amos');
INSERT INTO `bible_books` (`id`, `name`) VALUES (31, 'Obadiah');
INSERT INTO `bible_books` (`id`, `name`) VALUES (32, 'Jonah');
INSERT INTO `bible_books` (`id`, `name`) VALUES (33, 'Micah');
INSERT INTO `bible_books` (`id`, `name`) VALUES (34, 'Nahum');
INSERT INTO `bible_books` (`id`, `name`) VALUES (35, 'Habakkuk');
INSERT INTO `bible_books` (`id`, `name`) VALUES (36, 'Zephaniah');
INSERT INTO `bible_books` (`id`, `name`) VALUES (37, 'Haggai');
INSERT INTO `bible_books` (`id`, `name`) VALUES (38, 'Zechariah');
INSERT INTO `bible_books` (`id`, `name`) VALUES (39, 'Malachi');
INSERT INTO `bible_books` (`id`, `name`) VALUES (40, 'Matthew');
INSERT INTO `bible_books` (`id`, `name`) VALUES (41, 'Mark');
INSERT INTO `bible_books` (`id`, `name`) VALUES (42, 'Luke');
INSERT INTO `bible_books` (`id`, `name`) VALUES (43, 'John');
INSERT INTO `bible_books` (`id`, `name`) VALUES (44, 'Acts');
INSERT INTO `bible_books` (`id`, `name`) VALUES (45, 'Romans');
INSERT INTO `bible_books` (`id`, `name`) VALUES (46, '1 Corinthians');
INSERT INTO `bible_books` (`id`, `name`) VALUES (47, '2 Corinthians');
INSERT INTO `bible_books` (`id`, `name`) VALUES (48, 'Galatians');
INSERT INTO `bible_books` (`id`, `name`) VALUES (49, 'Ephesians');
INSERT INTO `bible_books` (`id`, `name`) VALUES (50, 'Philippians');
INSERT INTO `bible_books` (`id`, `name`) VALUES (51, 'Colossians');
INSERT INTO `bible_books` (`id`, `name`) VALUES (52, '1 Thessalonians');
INSERT INTO `bible_books` (`id`, `name`) VALUES (53, '2 Thessalonians');
INSERT INTO `bible_books` (`id`, `name`) VALUES (54, '1 Timothy');
INSERT INTO `bible_books` (`id`, `name`) VALUES (55, '2 Timothy');
INSERT INTO `bible_books` (`id`, `name`) VALUES (56, 'Titus');
INSERT INTO `bible_books` (`id`, `name`) VALUES (57, 'Philemon');
INSERT INTO `bible_books` (`id`, `name`) VALUES (58, 'Hebrews');
INSERT INTO `bible_books` (`id`, `name`) VALUES (59, 'James');
INSERT INTO `bible_books` (`id`, `name`) VALUES (60, '1 Peter');
INSERT INTO `bible_books` (`id`, `name`) VALUES (61, '2 Peter');
INSERT INTO `bible_books` (`id`, `name`) VALUES (62, '1 John');
INSERT INTO `bible_books` (`id`, `name`) VALUES (63, '2 John');
INSERT INTO `bible_books` (`id`, `name`) VALUES (64, '3 John');
INSERT INTO `bible_books` (`id`, `name`) VALUES (65, 'Jude');
INSERT INTO `bible_books` (`id`, `name`) VALUES (66, 'Revelation');
