INSERT INTO `bible_translations` (`name`, `code`) VALUES ('21st Century King James Version (KJ21)'                                ,  'KJ21'     ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('American Standard Version (ASV)'                                       ,  'ASV'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Amplified Bible (AMP)'                                                 ,  'AMP'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Amplified Bible , Classic Edition (AMPC)'                              ,  'AMPC'     ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('BRG Bible (BRG)'                                                       ,  'BRG'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Christian Standard Bible (CSB)'                                        ,  'CSB'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Common English Bible (CEB)'                                            ,  'CEB'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Complete Jewish Bible (CJB)'                                           ,  'CJB'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Contemporary English Version (CEV)'                                    ,  'CEV'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Darby Translation (DARBY)'                                             ,  'DARBY'    ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Disciples'' Literal New Testament (DLNT)'                              ,  'DLNT'     ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Douay-Rheims 1899 American Edition (DRA)'                              ,  'DRA'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Easy-to-Read Version (ERV)'                                            ,  'ERV'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Evangelical Heritage Version (EHV)'                                    ,  'EHV'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('English Standard Version (ESV)'                                        ,  'ESV'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('English Standard Version Anglicised (ESVUK)'                           ,  'ESVUK'    ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Expanded Bible (EXB)'                                                  ,  'EXB'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('1599 Geneva Bible (GNV)'                                               ,  'GNV'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('GOD’S WORD Translation (GW)'                                           ,  'GW'       ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Good News Translation (GNT)'                                           ,  'GNT'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Holman Christian Standard Bible (HCSB)'                                ,  'HCSB'     ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('International Children’s Bible (ICB)'                                  ,  'ICB'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('International Standard Version (ISV)'                                  ,  'ISV'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('J.B. Phillips New Testament (PHILLIPS)'                                ,  'PHILLIPS' ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Jubilee Bible 2000 (JUB)'                                              ,  'JUB'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('King James Version (KJV)'                                              ,  'KJV'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Authorized (King James) Version (AKJV)'                                ,  'AKJV'     ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Legacy Standard Bible (LSB)'                                           ,  'LSB'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Lexham English Bible (LEB)'                                            ,  'LEB'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Living Bible (TLB)'                                                    ,  'TLB'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('The Message (MSG)'                                                     ,  'MSG'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Modern English Version (MEV)'                                          ,  'MEV'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Mounce Reverse Interlinear New Testament (MOUNCE)'                     ,  'MOUNCE'   ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Names of God Bible (NOG)'                                              ,  'NOG'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('New American Bible (Revised Edition) (NABRE)'                          ,  'NABRE'    ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('New American Standard Bible (NASB)'                                    ,  'NASB'     ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('New American Standard Bible 1995 (NASB1995)'                           ,  'NASB1995' ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('New Catholic Bible (NCB)'                                              ,  'NCB'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('New Century Version (NCV)'                                             ,  'NCV'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('New English Translation (NET)'                                         ,  'NET'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('New International Reader''s Version (NIRV)'                            ,  'NIRV'     ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('New International Version (NIV)'                                       ,  'NIV'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('New International Version - UK (NIVUK)'                                ,  'NIVUK'    ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('New King James Version (NKJV)'                                         ,  'NKJV'     ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('New Life Version (NLV)'                                                ,  'NLV'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('New Living Translation (NLT)'                                          ,  'NLT'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('New Matthew Bible (NMB)'                                               ,  'NMB'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('New Revised Standard Version, Anglicised (NRSVA)'                      ,  'NRSVA'    ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('New Revised Standard Version, Anglicised Catholic Edition (NRSVACE)'   ,  'NRSVACE'  ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('New Revised Standard Version Catholic Edition (NRSVCE)'                ,  'NRSVCE'   ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('New Revised Standard Version Updated Edition (NRSVUE)'                 ,  'NRSVUE'   ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('New Testament for Everyone (NTE)'                                      ,  'NTE'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Orthodox Jewish Bible (OJB)'                                           ,  'OJB'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Revised Geneva Translation (RGT)'                                      ,  'RGT'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Revised Standard Version (RSV)'                                        ,  'RSV'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Revised Standard Version Catholic Edition (RSVCE)'                     ,  'RSVCE'    ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Tree of Life Version (TLV)'                                            ,  'TLV'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('The Voice (VOICE)'                                                     ,  'VOICE'    ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('World English Bible (WEB)'                                             ,  'WEB'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Worldwide English (New Testament) (WE)'                                ,  'WE'       ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Wycliffe Bible (WYC)'                                                  ,  'WYC'      ) ;
INSERT INTO `bible_translations` (`name`, `code`) VALUES ('Young’s Literal Translation (YLT)'                                     ,  'YLT'      ) ;
